// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuzonnsThings.Databases;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Backend.Models.Lobbies.LobbyModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LobbyCreator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LobbyEnded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LobbyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayersCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayersCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("PuzonnsThings.Models.Todo.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    b.Property<string>("TaskEndDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "TaskEndDateTime");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "TaskName");

                    b.Property<int>("TaskPriority")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "TaskPriority");

                    b.Property<int>("TaskProgressId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "TaskProgressId");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "UserId");

                    b.HasKey("Id");

                    b.ToTable("TodoList");
                });

            modelBuilder.Entity("PuzonnsThings.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    b.Property<float>("Coins")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "Coins");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "Password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
